In progress lisp implementation of juggler on meatfighter

* Setup
  We depend on the following git repositories:

  : git://github.com/nixeagle/Eos.git
  : git://github.com/nixeagle/nutils.git

  Please clone those and symlink them.

  Next use =asdf-install= to install =alexandria= and =cl-gd= if they are
  not already setup. =cl-gd= requires a bit of extra setup, after you
  install it vie asdf do the following to finalize the installation[fn:1]:

  : cd ~/.sbcl/site/cl-gd-0.5.7
  : gcc -fPIC -c cl-gd-glue.c
  : ld -lgd -lz -lpng -ljpeg -lfreetype -lm -shared cl-gd-glue.o -o cl-gd-glue.so
  : rm cl-gd-glue.o


  Now we also depend on lispbuilder-sdl. This depends on the C library
  libsdl. Please find and install that library using whatever distro tools
  required.

  Then we need to install another broken dependency called lift. The
  official version has a commit that breaks the library for anyone that
  does not have moptilities already loaded. Needless to say its far
  simpler to do =git clone git://github.com/nixeagle/lift.git= which is a
  version of lift without the breaking code. Symlink the library so that
  asdf will see it and try to do =(require :lift)=.

  Finally run =(asdf-install:install :lispbuilder-sdl)=.


* Footnotes

[fn:1] Assuming sbcl is used here, please change depending on what lisp
you are using.
